### ISSUE TITLE
How to resume the training?

### ISSUE THREAD

**Issue by DavisMeee** [jinsuyoo/act#2]
My experiment have saved two checkpoint files, one named last-v1.ckpt and one named last.ckpt. Now I am wondering about which one I should to choose for the resume train. Thanks a lot.

**Comment by jinsuyoo** [comment]
Thank you for your interest in our work! I think last.ckpt would be the right one. It's a little strange to have a checkpoint named like last-v1.ckpt because I believe the latest checkpoint always overwrites last.ckpt file.
