### ISSUE TITLE
About  Head Module

### ISSUE THREAD

**Issue by CR7forMadrid** [jinsuyoo/act#5]
Thank you for your great work, but the Head structure you used is  mentioned in the IPT 、EDSR， and what is the difference between this head and just a 3*3 convolutional layer?

**Comment by jinsuyoo** [comment]
Thank you for your interest in our work!

From my understanding, the head modules in your mentioned works include two additional common residual blocks. I believe this was intended to enlarge receptive fields before going into the body module, but don't think it has a significant purpose.

Best,

Jinsu
